INSERT INTO Field (FIELD_NAME) VALUES
	('Field 1'),
	('Field 2'),
	('Field 4'),
	('Field 5'),
	('Field 6'),
	('Field 7'),
	('Field 8'),
	('Field 9'),
	('Field 10'),
	('Field 11'),
	('Field 12'),
	('Field 13'),
	('Field 14'),
	('Field 15'),
	('Field 16'),
	('Field 17'),
	('Field 18'),
	('Field 19');
	